[build]
builder = "nixpacks"
buildCommand = "cd apps/worker && npm install"

[deploy]
startCommand = "cd apps/worker && npm run start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 30

[nixpacks]
pkgs = ["nodejs-18_x"]
cmds = ["npm install --prefix apps/worker"]
