[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:worker"

[deploy]
startCommand = "npm run start:worker"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60

[nixpacks]
pkgs = ["nodejs-18_x"]
