[build]
builder = "railpack"
buildCommand = "pnpm -F @dashboard/worker build"
watchPatterns = ["/apps/worker/**"]

[deploy]
startCommand = "pnpm -F @dashboard/worker start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
